wandb_version: 1

name:
  desc: null
  value: one_batch_test
n_gpu:
  desc: null
  value: 1
arch:
  desc: null
  value:
    type: DummyModel
    args:
      fc_hidden: 2
data:
  desc: null
  value:
    train:
      batch_size: 2
      num_workers: 0
      datasets:
      - type: ASVspoofDataset
        args:
          data_dir: data/test_data
          part: train
          limit: 2
    val:
      batch_size: 2
      num_workers: 0
      datasets:
      - type: ASVspoofDataset
        args:
          data_dir: data/test_data
          part: train
          limit: 2
optimizer:
  desc: null
  value:
    type: SGD
    args:
      lr: 0.01
loss:
  desc: null
  value:
    type: WeightedCE
    args:
      spoof_coef: 1.0
      bonafide_coef: 9.0
metrics:
  desc: null
  value:
  - type: EERMetric
    args: {}
lr_scheduler:
  desc: null
  value:
    type: OneCycleLR
    args:
      steps_per_epoch: 100
      epochs: 10
      anneal_strategy: cos
      max_lr: 0.01
      pct_start: 0.2
trainer:
  desc: null
  value:
    epochs: 10
    save_dir: saved/
    save_period: 300
    verbosity: 2
    visualize: wandb
    wandb_project: as_project
    len_epoch: 100
    grad_norm_clip: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.27.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1702391276.654378
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.9.7
      5: 0.14.2
      6: 4.27.3
      8:
      - 2
      - 5
